export default [
    
    
    {
      id: "1",
      categoryId: "2",
      name: "SamsungGalaxy Note20",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
      price: 179,
      image: "/uploads/SamsungGalaxyNote20.jpg",
      cpu: "1.3GHz Apple A6",
      camera: "8mp (3264x2448)",
      size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
      weight: "132 grams (4.7 ounces) with battery",
      display: "4.0 326 pixel density",
      battery: "1480 mAh",
      memory: "16GB, 32GB and RAM 1 GB"
    },
    {
      id: "2",
      categoryId: "1",
      name: "iPhone11 ProMax 512GB",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
      price: 953,
      image: "/uploads/iPhone11ProMax512GB.jpg",
      cpu: "1.3GHz Apple A6",
      camera: "8mp (3264x2448)",
      size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
      weight: "132 grams (4.7 ounces) with battery",
      display: "4.0 326 pixel density",
      battery: "1480 mAh",
      memory: "16GB, 32GB and RAM 1 GB"
    },
    {
      id: "3",
      categoryId: "2",
      name: "SamsungGalaxy Z Flip",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
      price: 953,
      image: "/uploads/SamsungGalaxyZFlip.jpg",
      cpu: "1.3GHz Apple A6",
      camera: "8mp (3264x2448)",
      size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
      weight: "132 grams (4.7 ounces) with battery",
      display: "4.0 326 pixel density",
      battery: "1480 mAh",
      memory: "16GB, 32GB and RAM 1 GB"
    },
    {
      id: "4",
      categoryId: "2",
      name: "SamsungGalaxy S20+",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
      price: 953,
      image: "/uploads/SamsungGalaxyS20+.jpg",
      cpu: "1.3GHz Apple A6",
      camera: "8mp (3264x2448)",
      size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
      weight: "132 grams (4.7 ounces) with battery",
      display: "4.0 326 pixel density",
      battery: "1480 mAh",
      memory: "16GB, 32GB and RAM 1 GB"
    },
    {
      id: "5",
      categoryId: "2",
      name: "SamsungGalaxy Z Fold",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
      price: 953,
      image: "/uploads/SamsungGalaxyZFold25G.jpg",
      cpu: "1.3GHz Apple A6",
      camera: "8mp (3264x2448)",
      size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
      weight: "132 grams (4.7 ounces) with battery",
      display: "4.0 326 pixel density",
      battery: "1480 mAh",
      memory: "16GB, 32GB and RAM 1 GB"
    },
//////////////////////////////////////

[
  {
    "id": "1",
    "categoryId": "1",
    "name": "Apple iPhone 5c",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    "price": 823,
    "image": "https://vn-test-11.slatic.net/p/c8f76c6f0f5d22c6a7f74c7b0285d24d.jpg_720x720q80.jpg_.webp",
    "cpu": "1.3GHz Apple A6",
    "camera": "8mp (3264x2448)",
    "size": "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    "weight": "132 grams (4.7 ounces) with battery",
    "display": "4.0 326 pixel density",
    "battery": "1480 mAh",
    "memory": "16GB, 32GB and RAM 1 GB",
    "status": false
  },
  {
    "id": "2",
    "categoryId": "1",
    "name": "Apple iPhone 6",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    "price": 953,
    "image": "https://cdn.tgdd.vn/Products/Images/42/92962/iphone-6-32gb-gold-hh-600x600-600x600-600x600.jpg",
    "cpu": "1.3GHz Apple A6",
    "camera": "8mp (3264x2448)",
    "size": "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    "weight": "132 grams (4.7 ounces) with battery",
    "display": "4.0 326 pixel density",
    "battery": "1480 mAh",
    "memory": "16GB, 32GB and RAM 1 GB",
    "status": false
  },
  {
    "id": "3",
    "categoryId": "4",
    "name": "Lenovo A6000",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    "price": 764,
    "image": "https://cf.shopee.vn/file/7066af0ad6607413d73271ca395fe4d4",
    "cpu": "1.3GHz Apple A6",
    "camera": "8mp (3264x2448)",
    "size": "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    "weight": "132 grams (4.7 ounces) with battery",
    "display": "4.0 326 pixel density",
    "battery": "1480 mAh",
    "memory": "16GB, 32GB and RAM 1 GB",
    "status": false
  },
  {
    "id": "4",
    "categoryId": "5",
    "name": "Nokia Lumia 1520",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    "price": 674,
    "image": "https://chamsocdidong.com/wp-content/uploads/2018/10/sua-loi-phan-mem-nokia-lumia-1520-ava.jpg",
    "cpu": "1.3GHz Apple A6",
    "camera": "8mp (3264x2448)",
    "size": "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    "weight": "132 grams (4.7 ounces) with battery",
    "display": "4.0 326 pixel density",
    "battery": "1480 mAh",
    "memory": "16GB, 32GB and RAM 1 GB",
    "status": false
  },
  {
    "id": "5",
    "categoryId": "3",
    "name": "HTC One",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    "price": 674,
    "image": "/uploads/htc-one-m7-802w-dual-sim-silver.jpg",
    "cpu": "1.3GHz Apple A6",
    "camera": "8mp (3264x2448)",
    "size": "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    "weight": "132 grams (4.7 ounces) with battery",
    "display": "4.0 326 pixel density",
    "battery": "1480 mAh",
    "memory": "16GB, 32GB and RAM 1 GB",
    "status": false
  },
  {
    "id": "6",
    "categoryId": "2",
    "name": "Samsung Galaxy S6",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    "price": 674,
    "image": "https://www.mytrendyphone.eu/images/Samsung-Galaxy-S6-Edge-32GB-Factory-Refurbished-Gold-Platinum-05072019-01-p.jpg",
    "cpu": "1.3GHz Apple A6",
    "camera": "8mp (3264x2448)",
    "size": "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    "weight": "132 grams (4.7 ounces) with battery",
    "display": "4.0 326 pixel density",
    "battery": "1480 mAh",
    "memory": "16GB, 32GB and RAM 1 GB",
    "status": false
  },
  {
    "id": "7",
    "categoryId": "1",
    "name": "iPhone XR 64GB",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    "price": 674,
    "image": "https://bachlongmobile.com/media/catalog/product/cache/2/image/040ec09b1e35df139433887a97daa66f/6/3/636748797175081877_iphone-xr-do_6.png",
    "cpu": "1.3GHz Apple A6",
    "camera": "8mp (3264x2448)",
    "size": "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    "weight": "132 grams (4.7 ounces) with battery",
    "display": "4.0 326 pixel density",
    "battery": "1480 mAh",
    "memory": "16GB, 32GB and RAM 1 GB",
    "status": false
  },
  {
    "id": "8",
    "categoryId": "1",
    "name": "iPhone 11 64GB",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    "price": 674,
    "image": "https://didongviet.vn/pub/media/catalog/product//i/p/iphone-11-didongviet_3_8.jpg",
    "cpu": "1.3GHz Apple A6",
    "camera": "8mp (3264x2448)",
    "size": "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    "weight": "132 grams (4.7 ounces) with battery",
    "display": "4.0 326 pixel density",
    "battery": "1480 mAh",
    "memory": "16GB, 32GB and RAM 1 GB",
    "status": false
  },
  {
    "id": "9",
    "categoryId": "2",
    "name": "SamsungGalaxy S20+",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    "price": 674,
    "image": "https://cdn.tgdd.vn/Files/2020/02/17/1237106/z4_600x617.jpg",
    "cpu": "1.3GHz Apple A6",
    "camera": "8mp (3264x2448)",
    "size": "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    "weight": "132 grams (4.7 ounces) with battery",
    "display": "4.0 326 pixel density",
    "battery": "1480 mAh",
    "memory": "16GB, 32GB and RAM 1 GB",
    "status": false
  },
  {
    "id": "10",
    "categoryId": "2",
    "name": "SamsungGalaxy Z Fold",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    "price": 674,
    "image": "https://www.didongmy.com/vnt_upload/product/FOLD/thumbs/600_samsung_galaxy_fold.jpg",
    "cpu": "1.3GHz Apple A6",
    "camera": "8mp (3264x2448)",
    "size": "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    "weight": "132 grams (4.7 ounces) with battery",
    "display": "4.0 326 pixel density",
    "battery": "1480 mAh",
    "memory": "16GB, 32GB and RAM 1 GB",
    "status": false
  }
]
    
  ]
  